config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  post 'convert_to_zip' => "home#convert_to_zip"
  post 'extract_from_zip' => "home#extract_from_zip"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/zip_converter.rb
class ZipConverter < ApplicationRecord
end

app/models/zip_extractor.rb
class ZipExtractor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @zip_converter = ZipConverter.new
    @zip_extractor = ZipExtractor.new
  end

  def convert_to_zip
    ZipService.convert_to_zip(params[:zip_converter])
  end

  def extract_from_zip
    ZipService.extract_from_zip(params[:zip_extractor])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="row mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 class="mb-4">Compress your folders in a zipfile</h3>
          <%= form_with(model: @zip_converter, url: convert_to_zip_path, method: :post) do |form| %>
            <div class="form-group">
              <%= form.label :folder_path, 'Folder Path', class: 'mb-1 fw-bold' %>
              <%= form.text_field :folder_path, class: 'form-control form-control-lg', placeholder: 'Enter folder path', required: true %>
              <small class="form-text text-muted">Enter the path to the folder you want to zip.</small>
            </div>
            <div class="form-group mt-4">
              <%= form.label :zip_folder_path, 'Zip Folder Path', class: 'mb-1 fw-bold' %>
              <%= form.text_field :zip_folder_path, class: 'form-control form-control-lg', placeholder: 'Enter zip path', required: true %>
              <small class="form-text text-muted">Enter the path for the folder where you want to place the zip file.</small>
            </div>
            <%= form.submit 'Convert to ZIP', class: 'btn btn-primary btn-lg mt-4' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 class="mb-4">Extract your zipfiles in a folder</h3>
          <%= form_with(model: @zip_extractor, url: extract_from_zip_path, method: :post) do |form| %>
            <div class="form-group">
              <%= form.label :compressed_file_path, 'Zip file Path', class: 'mb-1 fw-bold' %>
              <%= form.text_field :compressed_file_path, class: 'form-control form-control-lg', placeholder: 'Enter folder path', required: true %>
              <small class="form-text text-muted">Enter the path to the zip you want to extract.</small>
            </div>
            <div class="form-group mt-4">
              <%= form.label :extracted_file_path, 'Exracted Folder Path', class: 'mb-1 fw-bold' %>
              <%= form.text_field :extracted_file_path, class: 'form-control form-control-lg', placeholder: 'Enter zip path', required: true %>
              <small class="form-text text-muted">Enter the path for the folder where you want to place the extracted zip file.</small>
            </div>
            <%= form.submit 'Extract ZIP', class: 'btn btn-primary btn-lg mt-4' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZipAdda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>